<?php

namespace Proxies\__CG__\Application\TodoBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Task extends \Application\TodoBundle\Entity\Task implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setCreateddate($createddate)
    {
        $this->__load();
        return parent::setCreateddate($createddate);
    }

    public function getCreateddate()
    {
        $this->__load();
        return parent::getCreateddate();
    }

    public function setUpdateddate($updateddate)
    {
        $this->__load();
        return parent::setUpdateddate($updateddate);
    }

    public function getUpdateddate()
    {
        $this->__load();
        return parent::getUpdateddate();
    }

    public function setComments($comments)
    {
        $this->__load();
        return parent::setComments($comments);
    }

    public function getComments()
    {
        $this->__load();
        return parent::getComments();
    }

    public function addProgres(\Application\TodoBundle\Entity\Taskprogress $progress)
    {
        $this->__load();
        return parent::addProgres($progress);
    }

    public function removeProgres(\Application\TodoBundle\Entity\Taskprogress $progress)
    {
        $this->__load();
        return parent::removeProgres($progress);
    }

    public function getProgress()
    {
        $this->__load();
        return parent::getProgress();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function setAllocateddays($allocateddays)
    {
        $this->__load();
        return parent::setAllocateddays($allocateddays);
    }

    public function getAllocateddays()
    {
        $this->__load();
        return parent::getAllocateddays();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'name', 'comments', 'allocateddays', 'createddate', 'updateddate', 'progress');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}