<?php

namespace Application\TodoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TaskprogressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskprogressRepository extends EntityRepository
{
}
